### ISSUE TITLE
Hi! are you interested in maintaining this repo ?

### ISSUE THREAD

**Issue by aahnik** [lpellis/pydevto#1]
I am interested in adding some new features to the package:

- add type hint, and enhance docstrings for all the functions (so that it supports autocomplete and documentation is shown in modern editors)
- publishing a website for the documentation of the package. (auto generated by docstrings, using pdoc3) + hosted by github pages
- remove pydev.egg-info (why that's required ? )

some questions:

is there any alternative python packages that wraps dev.to api ? I searched, but found none.

if you are interested in maintaining this repo, i will submit a PR within a week, else i will start working on my own fork.

**Comment by lpellis** [comment]
You are welcome to submit a PR and I will merge it, I'm still using it for some my projects so updates are welcome.
pydev-egg is just an accidental artifact I believe.

There wasnt any other package available at the time I wrote this, but I havent checked recently.

**Comment by aahnik** [comment]
I made this issue just to make sure that everything is alive.

I will submit a PR soon, with the above mentioned changes.

Thank you for your quick response.

**Comment by aahnik** [comment]
https://github.com/lpellis/pydevto/pull/2#issuecomment-818046885
